//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Entity;
using RentalMVC2010.Models;

public class RentalDB : DbContext
{


    public DbSet<Unit> Units { get; set; }

    public DbSet<UnitGallery> UnitGallery { get; set; }

}
