//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RentalMVC2010.Models
{
    public partial class UnitGallery
    {
        public int Id { get; set; }
        public string Path { get; set; }
        public string Caption { get; set; }
        public int Rank { get; set; }
        public Nullable<int> Unit_UnitId { get; set; }
        public int UnitId { get; set; }
    
        public virtual Unit Unit_1 { get; set; }
    }
    
}
